apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    jenkins.openshift.io/generated-by: jenkins
    jenkins.openshift.io/job-path: sre/demo-app
  name: demo-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/slowtrailrunner/demo-app.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
